services:
  ffc-rps-experiment-api:
    build:
      context: .
      target: production
    image: ffc-rps-experiment-api
    container_name: ffc-rps-experiment-api
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-rps-experiment-api-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}

