environment: production
environmentCode:
name: ffc-rps-experiment-api
namespace: ffc-rps
workstream: ffc-rps
image: ffc-rps-experiment-api

labels:
  component: service

appInsights:
  connectionString:

containerConfigMap:
  name: ffc-rps-experiment-api-config-map

containerSecret:
  name: ffc-rps-experiment-api-container-secret
  type: Opaque

deployment: {}

container:
  requestMemory: 100Mi
  requestCpu: 100m
  limitMemory: 100Mi
  limitCpu: 100m
  port: 3000

livenessProbe:
  path: /healthz
  port: 3000
  initialDelaySeconds: 20
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5

readinessProbe:
  path: /healthy
  port: 3000
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5
